### ISSUE TITLE
缺乏一个使用实例是这个插件的死穴

### ISSUE THREAD

**Issue by kazaff** [goto100/ng-rap#1]
> Uncaught Error: No module: opensearchConfig

这个module是从哪获取？

**Comment by goto100** [comment]
不好意思刚看到。早期没有做其他项目的兼容性测试，目前你说的这个问题已经没有啦。

现在已经发布了0.2.0版，调用更加方便了，不用在页面上应用rap.js就可以使用，欢迎试用。
